Create STU0008Lex
BetaMasaheft/Studies pull request #10
Opened 2023-12-19 12:31 UTC by CarstenHoffmannMarburg

I created a record for the lexicon attested in BMLor321 as recommended by Eugenia.

2023-12-19 13:14 UTC, eu-genia requested changes

2023-12-19 13:14 UTC, eu-genia commented on new/STU0008Lex.xml
> +                    Contrary to <bibl><ptr target="bm:bm:Assemani1719Bibliotheca"/><citedRange unit="page">431</citedRange></bibl>
bm: only once

2023-12-19 13:14 UTC, eu-genia commented on new/STU0008Lex.xml
> +                    The Vocabulary is apparently taken from poetry and arranged by initial letter.
what is taken from poetry? The list of lemmata? definitions? not clear

2023-12-19 13:16 UTC, eu-genia commented on new/STU0008Lex.xml
> +                    The Vocabulary is apparently taken from poetry and arranged by initial letter.
now saw the comment to the MS. So then write 
"The Vocabulary lists terms apparantly encountered in poetic texts"

2023-12-19 15:24 UTC, eu-genia approved these changes

2023-12-20 10:10 UTC, thea-m approved these changes

2023-12-20 10:10 UTC, merged